// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mechsystem.Data;

#nullable disable

namespace mechsystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816171022_AddSnakeCaseNaming")]
    partial class AddSnakeCaseNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mechsystem.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("EnderecoCompleto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco_completo");

                    b.Property<int>("GarantiaPadraoDias")
                        .HasColumnType("integer")
                        .HasColumnName("garantia_padrao_dias");

                    b.Property<string>("MensagemRodape")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem_rodape");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<bool>("ObrigarVistoriaParaOS")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigar_vistoria_para_os");

                    b.Property<string>("SimboloMoeda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("simbolo_moeda");

                    b.Property<decimal>("TaxaMaoDeObra")
                        .HasColumnType("numeric")
                        .HasColumnName("taxa_mao_de_obra");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("ValidadeOrcamentoDias")
                        .HasColumnType("integer")
                        .HasColumnName("validade_orcamento_dias");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whats_app");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes");

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.ContatoOS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_contato");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_servico_id");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registrado_por");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_contatos_os");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_contatos_os_ordem_servico_id");

                    b.ToTable("contatos_os", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("PecaId")
                        .HasColumnType("integer")
                        .HasColumnName("peca_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Referencia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("referencia");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_estoque");

                    b.HasIndex("PecaId")
                        .HasDatabaseName("ix_movimentacoes_estoque_peca_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimentacoes_estoque_usuario_id");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorizadoPor")
                        .HasColumnType("text")
                        .HasColumnName("autorizado_por");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_autorizacao");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataPrevisaoEntrega")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_previsao_entrega");

                    b.Property<DateTime?>("DataPrevisaoInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_previsao_inicio");

                    b.Property<string>("DescricaoProblemaRelatado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_problema_relatado");

                    b.Property<string>("MeioAutorizacao")
                        .HasColumnType("text")
                        .HasColumnName("meio_autorizacao");

                    b.Property<string>("ServicoAExecutar")
                        .HasColumnType("text")
                        .HasColumnName("servico_a_executar");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenAcompanhamento")
                        .HasColumnType("text")
                        .HasColumnName("token_acompanhamento");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorMaoDeObra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_mao_de_obra");

                    b.Property<decimal>("ValorPecas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_pecas");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_ordens_servico");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_ordens_servico_veiculo_id");

                    b.ToTable("ordens_servico", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServicoPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("PecaId")
                        .HasColumnType("integer")
                        .HasColumnName("peca_id");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_base");

                    b.Property<decimal>("PrecoCustoSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_custo_snapshot");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_cobrado");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_pecas");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_pecas_ordem_servico_id");

                    b.HasIndex("PecaId")
                        .HasDatabaseName("ix_ordem_servico_pecas_peca_id");

                    b.ToTable("ordem_servico_pecas", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServicoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_servico_id");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_base");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<int?>("TempoEstimadoMinutosSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_estimado_minutos_snapshot");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_cobrado");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_servicos");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_servicos_ordem_servico_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_ordem_servico_servicos_servico_id");

                    b.ToTable("ordem_servico_servicos", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_atual");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_custo");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_venda");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_pecas");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_pecas_sku");

                    b.ToTable("pecas", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("TempoEstimadoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_estimado_minutos");

                    b.Property<decimal>("ValorPadrao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_padrao");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NomeCompleto = "Administrador",
                            PasswordHash = "$2a$11$uegyC1YafmGAkp2uMJmfje/iz6TbLTTiqJgps2rWvCNQFzymrQTza",
                            Perfil = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("mechsystem.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cor")
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_veiculos_cliente_id");

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.Vistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvariasJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("avarias_json");

                    b.Property<DateTime>("DataVistoria")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vistoria");

                    b.Property<int>("NivelCombustivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_combustivel");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("QuilometragemEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem_entrada");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TemChaveRoda")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_chave_roda");

                    b.Property<bool>("TemEstepe")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_estepe");

                    b.Property<bool>("TemMacaco")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_macaco");

                    b.Property<bool>("TemRadio")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_radio");

                    b.Property<bool>("TemTriangulo")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_triangulo");

                    b.HasKey("Id")
                        .HasName("pk_vistorias");

                    b.HasIndex("OrdemServicoId")
                        .IsUnique()
                        .HasDatabaseName("ix_vistorias_ordem_servico_id");

                    b.ToTable("vistorias", (string)null);
                });

            modelBuilder.Entity("mechsystem.Models.ContatoOS", b =>
                {
                    b.HasOne("mechsystem.Models.OrdemServico", "OrdemServico")
                        .WithMany("Contatos")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contatos_os_ordens_servico_ordem_servico_id");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("mechsystem.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("mechsystem.Models.Peca", "Peca")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_pecas_peca_id");

                    b.HasOne("mechsystem.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_usuarios_usuario_id");

                    b.Navigation("Peca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServico", b =>
                {
                    b.HasOne("mechsystem.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordens_servico_veiculos_veiculo_id");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServicoPeca", b =>
                {
                    b.HasOne("mechsystem.Models.OrdemServico", "OrdemServico")
                        .WithMany("PecasUtilizadas")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_pecas_ordens_servico_ordem_servico_id");

                    b.HasOne("mechsystem.Models.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_pecas_pecas_peca_id");

                    b.Navigation("OrdemServico");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServicoServico", b =>
                {
                    b.HasOne("mechsystem.Models.OrdemServico", "OrdemServico")
                        .WithMany("ServicosAExecutarList")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_servicos_ordens_servico_ordem_servico_id");

                    b.HasOne("mechsystem.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_servicos_servicos_servico_id");

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("mechsystem.Models.Veiculo", b =>
                {
                    b.HasOne("mechsystem.Models.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("mechsystem.Models.Vistoria", b =>
                {
                    b.HasOne("mechsystem.Models.OrdemServico", "OrdemServico")
                        .WithOne("Vistoria")
                        .HasForeignKey("mechsystem.Models.Vistoria", "OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vistorias_ordens_servico_ordem_servico_id");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("mechsystem.Models.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("mechsystem.Models.OrdemServico", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("PecasUtilizadas");

                    b.Navigation("ServicosAExecutarList");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("mechsystem.Models.Peca", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
